target 'GJCAR.COM' do
platform :ios, '7.0'
pod 'BaiduMapKit', '~> 2.9.1'
pod 'Masonry', '~> 0.6.4'
pod 'AFNetworking', '~> 3.0.4'
pod 'Alipay_SDK_iOS', '~> 15.2.0.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'JPush', '3.0.2'

# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'
# 集成微信
pod 'UMengUShare/Social/WeChat'

end
